### ISSUE TITLE
Logo issue

### ISSUE THREAD

**Issue by auzadventure** [LinxHQ/linxbooks#22]
http://localhost/test/linxbooks/linxbooks/index.php/lbInvoice/default/view/id/3

scandir(images/logo/,images/logo/): The system cannot find the file specified. (code: 2)

**Comment by linxbooksadmin** [comment]
fixed

**Comment by MrxC0d3r** [comment]
Seems like the issue is not fixed yet
scandir(images/logo/,images/logo/): The system cannot find the file specified. (code: 2)
C:\xampp\htdocs\qu\protected\modules\lbQuotation\views\default\_page_header.php(123)
